site_name: Laboratorios de Programación
site_url: https://alejandra-437.github.io/POO/
docs_dir: docs

theme:
  name: material
  features:
    - navigation.sections # agrupa por secciones en la barra izquierda
    - navigation.expand # deja todo expandido
    - toc.integrate # mete el indice (ToC) de la pagina en la barra izquierda
nav:
  - Inicio: index.md
  - Laboratorio 1:
      - Introduccion: laboratorio_1/introduccion.md
      - Que es POO: laboratorio_1/que-es-poo.md
      - Que es una clase: laboratorio_1/que-es-una-clase.md
      - Constructores: laboratorio_1/constructores.md
      - Modificadores de acceso: laboratorio_1/modificadores-de-acceso.md
      - Encapsulamiento: laboratorio_1/encapsulamiento.md
      - Uso de this y super: laboratorio_1/uso-de-this-y-super.md
      - Implementacion: laboratorio_1/implementacion.md
      - Que es un objeto: laboratorio_1/que-es-un-objeto.md
      - Anexos: laboratorio_1/anexos.md
