name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [main] # o master, según tu rama por defecto
  workflow_dispatch: # permite lanzarlo a mano desde la pestaña Actions

permissions:
  contents: write # necesario para hacer push a gh-pages
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          # REQUIREMENTS es opcional; el action ya usa MkDocs Material por defecto
